# Generated by Django 6.1 on 2026-09-09 10:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("internship", "Internship"),
                            ("research", "Research"),
                            ("volunteer", "Volunteer"),
                            ("part-time", "Part-Time"),
                            ("full-time", "Full-Time"),
                            ("freelance", "Freelance"),
                        ],
                        default="full-time",
                        max_length=20,
                    ),
                ),
                ("thumbnail", models.URLField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
