# Generated by Django 6.1 on 2026-09-14 08:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_project"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="category",
        ),
        migrations.RemoveField(
            model_name="project",
            name="link",
        ),
        migrations.AddField(
            model_name="project",
            name="project_image_url",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="project",
            name="project_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(default="Belum diisi", max_length=255),
            preserve_default=False,
        ),
    ]
