# Generated by Django 6.1 on 2026-09-20 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_project_category_remove_project_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("started_at", models.DateField()),
                ("ended_at", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
