# Generated by Django 6.1 on 2026-09-21 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_project_id_alter_project_tech_stack"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="tech_stack",
            field=models.CharField(default="", max_length=255),
        ),
    ]
